const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
    sendMessage:          (msg)                      => ipcRenderer.invoke("chat:send",                 msg),
    setMode:              (mode)                     => ipcRenderer.invoke("chat:setMode",              mode),
    setTokenKey:           (key)                     => ipcRenderer.invoke("chat:setTokenKey",          key),
    setTemperature:       (key)                      => ipcRenderer.invoke("chat:setTemperature",       key),
    setContextWindowKey:  (key)                      => ipcRenderer.invoke("chat:setContextWindowKey",  key),
    saveDocument:         (doc)                      => ipcRenderer.invoke("engine:save_document",      doc),
    loadDocument:         ()                         => ipcRenderer.invoke("engine:load_document"),
    deleteDocument:       (doc)                      => ipcRenderer.invoke("engine:delete_document",    doc),
    replicateDocument:    (doc)                      => ipcRenderer.invoke("engine:replicate_document", doc),
    mergeDocument:        (doc)                      => ipcRenderer.invoke("engine:merge_document",     doc),
    exportDocument:       (doc)                      => ipcRenderer.invoke("engine:export_document",    doc),
    updateCharacter:      (character)                => ipcRenderer.invoke("engine:updateCharacter",    character),
    spawnInstance: (config)                          => ipcRenderer.invoke("engine:spawn_instance",     config),
    ingestDocuments:    (paths)                      => ipcRenderer.invoke("rag:ingest",                paths),
    ingestGoogleSheets: (spreadsheetId)              => ipcRenderer.invoke("ingest-google-sheet",       spreadsheetId).then(res => console.log("Ingest result:", res)).catch(err => console.error(err)),
    engineIngestChats:  (instanceId, files)          => ipcRenderer.invoke("engine:ingest_documents", { instanceId, files }),
    loadModel: (modelName)                           => ipcRenderer.invoke("engine:loadModel", { modelName }),
    openGDDialog: ()                                 => ipcRenderer.invoke("open-gdrive-dialog"),
    updateEngine:      (key)                         => ipcRenderer.invoke("engine:update",             key),
    getEngineInstance: ()                            => ipcRenderer.invoke("engine:getEngineInstance"),
    spawnAgent: (config)                             => ipcRenderer.invoke("engine:spawnAgent", config),
    destroy: (config)                                => ipcRenderer.invoke("engine:deleteAgent", config),
    saveConfig: (config)                             => ipcRenderer.invoke("engine:save_config", config),
    loadConfig: ()                                   => ipcRenderer.invoke("engine:load_config"),  
    setGenerationMode: (genMode)                     => ipcRenderer.invoke("engine:set-generation-mode", genMode),
    getConfig: ()                                     => ipcRenderer.invoke("engine:get_config"),
    getAgent: (id)                                   => ipcRenderer.invoke("engine:getAgent",       id),
    attachAgent: (id, agent)                         => ipcRenderer.invoke("engine:attachAgent", id, agent),
    queryAgent:  (id, vector, k)                     => ipcRenderer.invoke("engine:queryAgent",              id, vector, k),
    ingestAgentDocuments: (id, docs)                 => ipcRenderer.invoke("engine:ingestDocuments", id, docs),
    generateAgentResponse: (agentId, model, prompt)  => ipcRenderer.invoke("engine:generateAgentResponse", agentId, model, prompt),
    hfLogin: ()                                      => ipcRenderer.invoke('hf-login'),
    msLogin: ()                                      => ipcRenderer.invoke('ms-login'),
  });
