// saguaro/native/ops/hamiltonian_superposition.h
// Copyright 2025 Verso Industries
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Quantum Superposition of Hamiltonians.
//
// Implements a learnable superposition of basis Hamiltonians:
//   H_eff(q,p) = Re(Σᵢ αᵢ Hᵢ(q,p))
//
// where αᵢ ∈ ℂ are normalized complex amplitudes (Σ|αᵢ|² = 1)
// generated by a VQC, enabling dynamic interpolation between
// different physical regimes.
//
// References:
//   - Schuld & Petruccione (2021). "Machine Learning with Quantum Computers"
//   - IBM Quantum Learning (2025). "VQC-based Operator Learning"

#ifndef TENSORFLOW_CORE_USER_OPS_HAMILTONIAN_SUPERPOSITION_H_
#define TENSORFLOW_CORE_USER_OPS_HAMILTONIAN_SUPERPOSITION_H_

#include "Eigen/Core"
#include "Eigen/Dense"
#include <complex>
#include <vector>
#include <cmath>

// SIMD intrinsics
#if defined(__AVX512F__)
#include <immintrin.h>
#elif defined(__AVX2__)
#include <immintrin.h>
#elif defined(__ARM_NEON)
#include <arm_neon.h>
#endif

namespace tensorflow {

using Eigen::MatrixXf;
using Eigen::VectorXf;
using Eigen::Map;
using cfloat = std::complex<double>;  // F1 quality: Use double precision for quantum amplitude calculations

// =============================================================================
// Hamiltonian Basis Structure
// =============================================================================

/**
 * @brief A single Hamiltonian basis term.
 *
 * Each basis Hamiltonian has its own network weights, allowing
 * different "physical regimes" (kinetic-dominated, potential-dominated,
 * oscillatory, dissipative, etc.) to be learned independently.
 */
struct HamiltonianBasisTerm {
    MatrixXf W1;     // First layer weights: (h_input_dim, hidden_dim)
    VectorXf b1;     // First layer bias
    MatrixXf W2;     // Second layer weights: (hidden_dim, hidden_dim)
    VectorXf b2;     // Second layer bias
    MatrixXf W3;     // Output layer weights: (hidden_dim, 1)
    float b3;        // Output bias (scalar)
    
    // Physical interpretation hint
    std::string regime_name;  // e.g., "kinetic", "potential", "oscillatory"
};

/**
 * @brief Collection of basis Hamiltonians for superposition.
 *
 * The superposition allows the model to interpolate between regimes:
 *   - α₁ large, others small → kinetic-dominated
 *   - α₂ large → potential-dominated
 *   - balanced α→ mixed dynamics
 */
struct HamiltonianBasis {
    std::vector<HamiltonianBasisTerm> terms;
    int num_basis;      // Number of basis Hamiltonians (k)
    int h_input_dim;    // Input dimension to each HNN
    int hidden_dim;     // Hidden layer dimension
    
    HamiltonianBasis() : num_basis(0), h_input_dim(0), hidden_dim(0) {}
    
    HamiltonianBasis(int k, int input_dim, int h_dim)
        : num_basis(k), h_input_dim(input_dim), hidden_dim(h_dim) {
        terms.resize(k);
    }
    
    /**
     * @brief Initialize basis terms with provided weights.
     */
    void set_term(int idx, const MatrixXf& w1, const VectorXf& b1,
                  const MatrixXf& w2, const VectorXf& b2,
                  const MatrixXf& w3, float b3,
                  const std::string& name = "") {
        if (idx < 0 || idx >= num_basis) return;
        terms[idx].W1 = w1;
        terms[idx].b1 = b1;
        terms[idx].W2 = w2;
        terms[idx].b2 = b2;
        terms[idx].W3 = w3;
        terms[idx].b3 = b3;
        terms[idx].regime_name = name;
    }
};

// =============================================================================
// Complex Amplitude Utilities
// =============================================================================

/**
 * @brief Normalizes complex amplitudes to satisfy Σ|αᵢ|² = 1.
 *
 * @param alphas Array of complex amplitudes
 * @param num_basis Number of amplitudes
 */
inline void normalize_amplitudes(cfloat* alphas, int num_basis) {
    float norm_sq = 0.0f;
    for (int i = 0; i < num_basis; ++i) {
        norm_sq += std::norm(alphas[i]);  // |αᵢ|²
    }
    if (norm_sq > 1e-10f) {
        float inv_norm = 1.0f / std::sqrt(norm_sq);
        for (int i = 0; i < num_basis; ++i) {
            alphas[i] *= inv_norm;
        }
    } else {
        // Fallback: uniform distribution
        cfloat uniform(1.0f / std::sqrt(static_cast<float>(num_basis)), 0.0f);
        for (int i = 0; i < num_basis; ++i) {
            alphas[i] = uniform;
        }
    }
}

/**
 * @brief Computes diversity metric: Var(|α|²) to measure superposition spread.
 *
 * Higher variance indicates more peaked (less superposition).
 * Lower variance (near 1/k) indicates more uniform superposition.
 *
 * @param alphas Normalized complex amplitudes
 * @param num_basis Number of amplitudes
 * @return Variance of |α|² distribution
 */
inline float compute_alpha_diversity(const cfloat* alphas, int num_basis) {
    if (num_basis <= 1) return 0.0f;
    
    float mean = 1.0f / static_cast<float>(num_basis);  // E[|α|²] = 1/k for normalized
    float variance = 0.0f;
    
    for (int i = 0; i < num_basis; ++i) {
        float p_i = std::norm(alphas[i]);
        variance += (p_i - mean) * (p_i - mean);
    }
    variance /= static_cast<float>(num_basis);
    
    return variance;
}

// =============================================================================
// Intermediate State for Superposition
// =============================================================================

/**
 * @brief Intermediate states from all basis Hamiltonians.
 *
 * Stores per-basis hidden activations for gradient computation.
 */
struct SuperpositionIntermediate {
    std::vector<VectorXf> h1_per_basis;  // First hidden layer per basis
    std::vector<VectorXf> a1_per_basis;  // First activation per basis
    std::vector<VectorXf> h2_per_basis;  // Second hidden layer per basis
    std::vector<VectorXf> a2_per_basis;  // Second activation per basis
    std::vector<float> H_per_basis;       // Scalar Hamiltonian per basis
    float H_eff;                          // Effective (superposed) Hamiltonian
    VectorXf z;                           // Input state vector
};

// =============================================================================
// Superposition Hamiltonian Computation
// =============================================================================

/**
 * @brief Computes single basis Hamiltonian Hᵢ(q,p).
 *
 * Uses sin activation for each hidden layer (matching HNN convention).
 *
 * @param z Input state vector [q; p; x]
 * @param term Basis Hamiltonian term (weights)
 * @param out_h1 Output: first hidden pre-activation
 * @param out_a1 Output: first hidden activation
 * @param out_h2 Output: second hidden pre-activation
 * @param out_a2 Output: second hidden activation
 * @return Hᵢ(z) scalar value
 */
inline float compute_basis_H(
    const VectorXf& z,
    const HamiltonianBasisTerm& term,
    VectorXf& out_h1,
    VectorXf& out_a1,
    VectorXf& out_h2,
    VectorXf& out_a2) {
    
    // Layer 1: h1 = W1ᵀz + b1, a1 = sin(h1)
    out_h1 = term.W1.transpose() * z + term.b1;
    out_a1 = out_h1.array().sin();
    
    // Layer 2: h2 = W2ᵀa1 + b2, a2 = sin(h2)
    out_h2 = term.W2.transpose() * out_a1 + term.b2;
    out_a2 = out_h2.array().sin();
    
    // Output: H = W3ᵀa2 + b3
    float H = (term.W3.transpose() * out_a2)(0, 0) + term.b3;
    return H;
}

/**
 * @brief Computes effective superposition Hamiltonian.
 *
 * H_eff(z) = Re(Σᵢ αᵢ Hᵢ(z))
 *
 * Since Hᵢ are real, this simplifies to:
 * H_eff = Σᵢ Re(αᵢ) Hᵢ(z)
 *
 * @param z Input state vector
 * @param alphas Complex amplitudes (normalized)
 * @param basis Hamiltonian basis collection
 * @param intermediates Output: per-basis intermediate states
 * @return H_eff scalar
 */
inline float compute_superposition_H(
    const VectorXf& z,
    const cfloat* alphas,
    const HamiltonianBasis& basis,
    SuperpositionIntermediate& intermediates) {
    
    const int k = basis.num_basis;
    intermediates.z = z;
    intermediates.h1_per_basis.resize(k);
    intermediates.a1_per_basis.resize(k);
    intermediates.h2_per_basis.resize(k);
    intermediates.a2_per_basis.resize(k);
    intermediates.H_per_basis.resize(k);
    
    float H_eff = 0.0f;
    
    for (int i = 0; i < k; ++i) {
        float H_i = compute_basis_H(
            z, basis.terms[i],
            intermediates.h1_per_basis[i],
            intermediates.a1_per_basis[i],
            intermediates.h2_per_basis[i],
            intermediates.a2_per_basis[i]);
        
        intermediates.H_per_basis[i] = H_i;
        
        // H_eff += Re(αᵢ) * Hᵢ
        H_eff += alphas[i].real() * H_i;
    }
    
    intermediates.H_eff = H_eff;
    return H_eff;
}

// =============================================================================
// Gradient of Superposition Hamiltonian
// =============================================================================

/**
 * @brief Computes dHᵢ/dz for a single basis Hamiltonian.
 *
 * Uses stored intermediates for efficiency.
 *
 * @param intermediates Per-basis intermediate states
 * @param basis_idx Index of basis term
 * @param term Basis Hamiltonian term (weights)
 * @return dHᵢ/dz gradient vector
 */
inline VectorXf compute_basis_dH_dz(
    const SuperpositionIntermediate& intermediates,
    int basis_idx,
    const HamiltonianBasisTerm& term) {
    
    // Backprop through output layer
    VectorXf dH_da2 = term.W3.col(0);  // Shape: (hidden_dim,)
    
    // Backprop through sin activation: d/dh2 = cos(h2)
    VectorXf cos_h2 = intermediates.h2_per_basis[basis_idx].array().cos();
    VectorXf dH_dh2 = dH_da2.array() * cos_h2.array();
    
    // Backprop through layer 2
    VectorXf dH_da1 = term.W2 * dH_dh2;
    
    // Backprop through sin activation
    VectorXf cos_h1 = intermediates.h1_per_basis[basis_idx].array().cos();
    VectorXf dH_dh1 = dH_da1.array() * cos_h1.array();
    
    // Backprop through layer 1
    VectorXf dH_dz = term.W1 * dH_dh1;
    
    return dH_dz;
}

/**
 * @brief Computes gradient of effective Hamiltonian dH_eff/dz.
 *
 * dH_eff/dz = Σᵢ Re(αᵢ) dHᵢ/dz
 *
 * @param intermediates Per-basis intermediate states
 * @param alphas Complex amplitudes
 * @param basis Hamiltonian basis collection
 * @return dH_eff/dz gradient vector
 */
inline VectorXf compute_superposition_dH_dz(
    const SuperpositionIntermediate& intermediates,
    const cfloat* alphas,
    const HamiltonianBasis& basis) {
    
    const int k = basis.num_basis;
    VectorXf dH_eff_dz = VectorXf::Zero(intermediates.z.size());
    
    for (int i = 0; i < k; ++i) {
        VectorXf dH_i_dz = compute_basis_dH_dz(intermediates, i, basis.terms[i]);
        dH_eff_dz += alphas[i].real() * dH_i_dz;
    }
    
    return dH_eff_dz;
}

// =============================================================================
// Superposition Integration Step
// =============================================================================

/**
 * @brief Structure to hold superposition step results.
 */
struct SuperpositionStepResult {
    VectorXf q_next;
    VectorXf p_next;
    VectorXf output_proj;   // Projected output
    float H_initial;        // Initial effective Hamiltonian
    float H_final;          // Final effective Hamiltonian
    float alpha_diversity;  // Diversity of amplitude distribution
    std::vector<float> H_per_basis;  // Individual basis contributions
};

/**
 * @brief Performs single integration step with superposed Hamiltonian.
 *
 * Uses leapfrog integration with the effective superposed Hamiltonian:
 *   p_half = p - (dt/2) * dH_eff/dq
 *   q_next = q + dt * dH_eff/dp
 *   p_next = p_half - (dt/2) * dH_eff/dq
 *
 * @param q Current position
 * @param p Current momentum
 * @param x_t Input features
 * @param alphas Complex amplitudes from VQC
 * @param basis Hamiltonian basis
 * @param W_out Output projection weights
 * @param b_out Output projection bias
 * @param dt Timestep
 * @param state_dim Dimension of q/p
 * @return SuperpositionStepResult with evolved state and metrics
 */
inline SuperpositionStepResult superposition_leapfrog_step(
    const VectorXf& q,
    const VectorXf& p,
    const VectorXf& x_t,
    const cfloat* alphas,
    const HamiltonianBasis& basis,
    const Map<const MatrixXf>& W_out,
    const Map<const VectorXf>& b_out,
    float dt,
    int state_dim) {
    
    SuperpositionStepResult result;
    result.alpha_diversity = compute_alpha_diversity(alphas, basis.num_basis);
    
    // Concatenate state
    const int h_input_dim = 2 * state_dim + x_t.size();
    VectorXf z(h_input_dim);
    z << q, p, x_t;
    
    // Compute initial H_eff and gradient
    SuperpositionIntermediate int1;
    result.H_initial = compute_superposition_H(z, alphas, basis, int1);
    result.H_per_basis = int1.H_per_basis;
    
    VectorXf dH_dz1 = compute_superposition_dH_dz(int1, alphas, basis);
    
    // Leapfrog step 1: p_half = p - (dt/2) * dH/dq
    VectorXf dH_dq1 = dH_dz1.head(state_dim);
    VectorXf p_half = p - (dt / 2.0f) * dH_dq1;
    
    // Update z for step 2
    z.segment(state_dim, state_dim) = p_half;
    SuperpositionIntermediate int2;
    compute_superposition_H(z, alphas, basis, int2);
    VectorXf dH_dz2 = compute_superposition_dH_dz(int2, alphas, basis);
    
    // Leapfrog step 2: q_next = q + dt * dH/dp
    VectorXf dH_dp2 = dH_dz2.segment(state_dim, state_dim);
    VectorXf q_next = q + dt * dH_dp2;
    
    // Update z for step 3
    z.head(state_dim) = q_next;
    SuperpositionIntermediate int3;
    compute_superposition_H(z, alphas, basis, int3);
    VectorXf dH_dz3 = compute_superposition_dH_dz(int3, alphas, basis);
    
    // Leapfrog step 3: p_next = p_half - (dt/2) * dH/dq
    VectorXf dH_dq3 = dH_dz3.head(state_dim);
    VectorXf p_next = p_half - (dt / 2.0f) * dH_dq3;
    
    // Compute final H_eff
    z.head(state_dim) = q_next;
    z.segment(state_dim, state_dim) = p_next;
    SuperpositionIntermediate int_final;
    result.H_final = compute_superposition_H(z, alphas, basis, int_final);
    
    // Output projection
    VectorXf final_state(2 * state_dim);
    final_state << q_next, p_next;
    result.output_proj = W_out.transpose() * final_state + b_out;
    
    result.q_next = q_next;
    result.p_next = p_next;
    
    return result;
}

} // namespace tensorflow

#endif // TENSORFLOW_CORE_USER_OPS_HAMILTONIAN_SUPERPOSITION_H_
