"""Language policies for Saguaro's static math extraction."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class LanguagePolicy:
    """Math extraction policy for one language family."""

    language: str
    line_comment_markers: tuple[str, ...]
    block_comment_pairs: tuple[tuple[str, str], ...] = ()
    statement_terminators: tuple[str, ...] = ()
    assignment_tokens: tuple[str, ...] = ("=",)
    compound_assignment_tokens: tuple[str, ...] = ("+=", "-=", "*=", "/=", "%=")
    return_keywords: tuple[str, ...] = ("return",)
    loop_keywords: tuple[str, ...] = ("for", "while")
    newline_statements: bool = True
    ignore_prefixes: tuple[str, ...] = ()
    documentation_markers: tuple[str, ...] = ()
    math_function_names: tuple[str, ...] = field(
        default_factory=lambda: (
            "sum",
            "dot",
            "matmul",
            "sqrt",
            "exp",
            "log",
            "sin",
            "cos",
            "norm",
        )
    )


_POLICIES: dict[str, LanguagePolicy] = {
    "markdown": LanguagePolicy("markdown", line_comment_markers=()),
    "python": LanguagePolicy(
        "python",
        line_comment_markers=("#",),
        block_comment_pairs=(('"""', '"""'), ("'''", "'''")),
        loop_keywords=("for", "while"),
        ignore_prefixes=("if ", "elif ", "class ", "def ", "match ", "case "),
    ),
    "cpp": LanguagePolicy(
        "cpp",
        line_comment_markers=("//",),
        block_comment_pairs=(("/*", "*/"),),
        statement_terminators=(";",),
        loop_keywords=("for", "while"),
        ignore_prefixes=("if ", "switch ", "case ", "template ", "class ", "struct "),
    ),
    "cpp_header": LanguagePolicy(
        "cpp_header",
        line_comment_markers=("//",),
        block_comment_pairs=(("/*", "*/"),),
        statement_terminators=(";",),
        loop_keywords=("for", "while"),
        ignore_prefixes=("if ", "switch ", "case ", "template ", "class ", "struct "),
    ),
    "c": LanguagePolicy(
        "c",
        line_comment_markers=("//",),
        block_comment_pairs=(("/*", "*/"),),
        statement_terminators=(";",),
        loop_keywords=("for", "while"),
        ignore_prefixes=("if ", "switch ", "case ", "struct "),
    ),
    "objective_c": LanguagePolicy(
        "objective_c",
        line_comment_markers=("//",),
        block_comment_pairs=(("/*", "*/"),),
        statement_terminators=(";",),
        loop_keywords=("for", "while"),
        ignore_prefixes=("if ", "@interface", "@implementation", "@protocol", "- ("),
    ),
    "go": LanguagePolicy(
        "go",
        line_comment_markers=("//",),
        block_comment_pairs=(("/*", "*/"),),
        statement_terminators=(";",),
        loop_keywords=("for",),
        ignore_prefixes=("if ", "switch ", "case ", "func ", "type "),
    ),
    "rust": LanguagePolicy(
        "rust",
        line_comment_markers=("//",),
        block_comment_pairs=(("/*", "*/"),),
        statement_terminators=(";",),
        loop_keywords=("for", "while", "loop"),
        ignore_prefixes=("if ", "match ", "fn ", "struct ", "enum "),
    ),
    "java": LanguagePolicy(
        "java",
        line_comment_markers=("//",),
        block_comment_pairs=(("/*", "*/"),),
        statement_terminators=(";",),
        loop_keywords=("for", "while"),
        ignore_prefixes=("if ", "switch ", "case ", "class ", "interface "),
    ),
    "scala": LanguagePolicy(
        "scala",
        line_comment_markers=("//",),
        block_comment_pairs=(("/*", "*/"),),
        statement_terminators=(";",),
        loop_keywords=("for", "while"),
        ignore_prefixes=("if ", "match ", "case ", "class ", "object "),
    ),
    "solidity": LanguagePolicy(
        "solidity",
        line_comment_markers=("//",),
        block_comment_pairs=(("/*", "*/"),),
        statement_terminators=(";",),
        loop_keywords=("for", "while"),
        ignore_prefixes=("if ", "contract ", "struct ", "event ", "modifier "),
    ),
    "hdl": LanguagePolicy(
        "hdl",
        line_comment_markers=("--", "//"),
        statement_terminators=(";",),
        assignment_tokens=("<=", "="),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=("for", "while", "generate"),
        ignore_prefixes=("if ", "process", "entity ", "architecture ", "module "),
    ),
    "fortran": LanguagePolicy(
        "fortran",
        line_comment_markers=("!",),
        assignment_tokens=("=",),
        compound_assignment_tokens=(),
        return_keywords=("return",),
        loop_keywords=("do", "for"),
        ignore_prefixes=("if ", "module ", "subroutine ", "function ", "program "),
    ),
    "r": LanguagePolicy(
        "r",
        line_comment_markers=("#",),
        assignment_tokens=("<-", "=",),
        compound_assignment_tokens=(),
        return_keywords=("return",),
        loop_keywords=("for", "while"),
        ignore_prefixes=("if ", "function(", "function ("),
    ),
    "julia": LanguagePolicy(
        "julia",
        line_comment_markers=("#",),
        assignment_tokens=("=",),
        compound_assignment_tokens=(),
        return_keywords=("return",),
        loop_keywords=("for", "while"),
        ignore_prefixes=("if ", "function ", "struct ", "mutable struct "),
    ),
    "matlab": LanguagePolicy(
        "matlab",
        line_comment_markers=("%",),
        block_comment_pairs=(("%{", "%}"),),
        statement_terminators=(";",),
        assignment_tokens=("=",),
        compound_assignment_tokens=(),
        return_keywords=("return",),
        loop_keywords=("for", "while", "parfor"),
        ignore_prefixes=("if ", "function ", "classdef ", "switch "),
    ),
    "nim": LanguagePolicy(
        "nim",
        line_comment_markers=("#",),
        assignment_tokens=("=",),
        compound_assignment_tokens=("+=", "-=", "*=", "/=", "%="),
        return_keywords=("return",),
        loop_keywords=("for", "while"),
        ignore_prefixes=("if ", "elif ", "proc ", "template ", "type ", "macro "),
    ),
    "pascal": LanguagePolicy(
        "pascal",
        line_comment_markers=("//",),
        block_comment_pairs=(("(*", "*)"), ("{", "}")),
        statement_terminators=(";",),
        assignment_tokens=(":=", "="),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=("for", "while", "repeat"),
        ignore_prefixes=("if ", "procedure ", "function ", "unit ", "program ", "type "),
    ),
    "ada": LanguagePolicy(
        "ada",
        line_comment_markers=("--",),
        statement_terminators=(";",),
        assignment_tokens=(":=", "="),
        compound_assignment_tokens=(),
        return_keywords=("return",),
        loop_keywords=("for", "while", "loop"),
        ignore_prefixes=("if ", "procedure ", "function ", "package ", "type "),
    ),
    "cobol": LanguagePolicy(
        "cobol",
        line_comment_markers=("*>",),
        assignment_tokens=("=",),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=("perform",),
        ignore_prefixes=(
            "identification division",
            "environment division",
            "data division",
            "procedure division",
            "program-id",
        ),
    ),
    "config": LanguagePolicy(
        "config",
        line_comment_markers=("#", ";", "//"),
        assignment_tokens=("=", ":"),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=(),
    ),
    "bazel": LanguagePolicy(
        "bazel",
        line_comment_markers=("#",),
        assignment_tokens=("=",),
        compound_assignment_tokens=(),
        return_keywords=("return",),
        loop_keywords=("for",),
        ignore_prefixes=("if ", "def ", "load(", "package(", "exports_files("),
    ),
    "css": LanguagePolicy(
        "css",
        line_comment_markers=(),
        block_comment_pairs=(("/*", "*/"),),
        statement_terminators=(";",),
        assignment_tokens=(),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=(),
    ),
    "html": LanguagePolicy(
        "html",
        line_comment_markers=(),
        block_comment_pairs=(("<!--", "-->"),),
        assignment_tokens=(),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=(),
    ),
    "jinja": LanguagePolicy(
        "jinja",
        line_comment_markers=(),
        block_comment_pairs=(("{#", "#}"),),
        assignment_tokens=(),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=(),
    ),
    "clojure": LanguagePolicy(
        "clojure",
        line_comment_markers=(";;", ";"),
        assignment_tokens=(),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=(),
    ),
    "lisp": LanguagePolicy(
        "lisp",
        line_comment_markers=(";;", ";"),
        assignment_tokens=(),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=(),
    ),
    "elixir": LanguagePolicy(
        "elixir",
        line_comment_markers=("#",),
        assignment_tokens=("=",),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=("for",),
        ignore_prefixes=("if ", "defmodule ", "def ", "case ", "cond ", "fn "),
    ),
    "erlang": LanguagePolicy(
        "erlang",
        line_comment_markers=("%",),
        statement_terminators=(".",),
        assignment_tokens=("=",),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=(),
        ignore_prefixes=("-module", "-export", "-record"),
    ),
    "haskell": LanguagePolicy(
        "haskell",
        line_comment_markers=("--",),
        block_comment_pairs=(("{-", "-}"),),
        assignment_tokens=("=",),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=(),
        ignore_prefixes=("if ", "module ", "data ", "type ", "newtype "),
    ),
    "ocaml": LanguagePolicy(
        "ocaml",
        line_comment_markers=(),
        block_comment_pairs=(("(*", "*)"),),
        assignment_tokens=("<-", "="),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=("for", "while"),
        ignore_prefixes=("if ", "module ", "type ", "class "),
    ),
    "assembly": LanguagePolicy(
        "assembly",
        line_comment_markers=(";", "#", "//"),
        assignment_tokens=(),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=(),
    ),
    "latex": LanguagePolicy(
        "latex",
        line_comment_markers=("%",),
        assignment_tokens=(),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=(),
    ),
    "hcl": LanguagePolicy(
        "hcl",
        line_comment_markers=("#", "//"),
        block_comment_pairs=(("/*", "*/"),),
        assignment_tokens=("=", ":"),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=(),
    ),
    "qml": LanguagePolicy(
        "qml",
        line_comment_markers=("//",),
        block_comment_pairs=(("/*", "*/"),),
        statement_terminators=(";",),
        assignment_tokens=("=", ":"),
        compound_assignment_tokens=(),
        return_keywords=("return",),
        loop_keywords=("for", "while"),
        ignore_prefixes=("if ", "function ", "property ", "signal "),
    ),
    "emacs_lisp": LanguagePolicy(
        "emacs_lisp",
        line_comment_markers=(";;", ";"),
        assignment_tokens=(),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=(),
    ),
    "wat": LanguagePolicy(
        "wat",
        line_comment_markers=(";;", ";"),
        assignment_tokens=(),
        compound_assignment_tokens=(),
        return_keywords=(),
        loop_keywords=(),
    ),
}


_ALIASES = {
    "javascript": "java",
    "typescript": "java",
    "actionscript": "java",
    "aql": "config",
    "asciidoc": "markdown",
    "awk": "shell",
    "zig": "cpp",
    "coldfusion": "html",
    "crystal": "python",
    "csv": "config",
    "cypher": "config",
    "dlang": "cpp",
    "django_template": "jinja",
    "php": "cpp",
    "docker": "config",
    "ejs": "jinja",
    "flatbuffers": "cpp",
    "fsharp": "haskell",
    "gdscript": "python",
    "graphql": "config",
    "hack": "cpp",
    "handlebars": "html",
    "ini": "config",
    "json": "config",
    "lua": "python",
    "make": "config",
    "mdx": "markdown",
    "mql": "config",
    "nix": "config",
    "octave": "matlab",
    "org": "markdown",
    "perl": "python",
    "pli": "config",
    "powershell": "python",
    "prolog": "erlang",
    "proto": "config",
    "pug": "html",
    "puppet": "config",
    "rpg": "config",
    "rst": "markdown",
    "shell": "python",
    "ruby": "python",
    "sed": "shell",
    "smalltalk": "lisp",
    "sql": "config",
    "swift": "cpp",
    "tcl": "python",
    "thrift": "config",
    "toml": "config",
    "typst": "markdown",
    "unrealscript": "cpp",
    "vim": "config",
    "wolfram": "matlab",
    "xml": "html",
    "yaml": "config",
    "kotlin": "java",
    "csharp": "java",
    "cmake": "config",
    "vlang": "cpp",
}


def policy_for(language: str) -> LanguagePolicy:
    """Return the math extraction policy for one language."""

    normalized = str(language or "").strip().lower()
    normalized = _ALIASES.get(normalized, normalized)
    return _POLICIES.get(normalized, _POLICIES["python"])


def supported_languages() -> set[str]:
    """Return the set of languages with explicit math policies."""

    return set(_POLICIES) | set(_ALIASES)
